# Generated by Django 5.2.8 on 2025-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacteos', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacteo',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='productos/'),
        ),
    ]
